version: '3.3'

services:
   wordpress:
     image: wordpress:latest
     links:
       - wordpress_db:mysql
     volumes:
       - ./wp-config.php:/var/www/html/wp-config.php
       - ./twentynineteen-child:/var/www/html/wp-content/themes/twentynineteen-child
     ports:
       - "80:80"
     restart: always
     depends_on:
       - wordpress_db
   wordpress_db:
     image: mariadb
     volumes:
       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: password
   phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     links:
       - wordpress_db:db
     ports:
       - 8181:80
     restart: always
     depends_on:
       - wordpress_db
volumes:
    wordpress_files:
    db_data:
