version: '3.3'

services:
   wordpress:
     image: wordpress:latest
     links:
       - wordpress_db:mysql
     volumes:
       - ./wordpress_files:/var/www/html
       - ./twentynineteen-child:/var/www/html/wp-content/themes/twentynineteen-child
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: password
   wordpress_db:
     image: mariadb
     volumes:
       - ./db_data:/var/lib/mysql
       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: password
   phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     links:
       - wordpress_db:db
     ports:
       - 8181:80
volumes:
    wordpress_files:
    db_data:
    docker-entrypoint-initdb.d:
